### ISSUE TITLE
File version timeline

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-ui-data-tracker#176] opened 2019-04-17 14:39 UTC
Users should be able to browse a file's version history under the file's page. This history should display a list of versions for the file, the time the version was created, and allow the user to download them.

**Comment by bdolly** [comment] 2019-04-17 19:52
no current design exists for this, will need to create one and link in ticket

**Comment by bdolly** [comment] 2019-05-08 16:54
File Version Detail View mockup https://invis.io/2RQP4OEUAS3#/362055881_5-1_Study_Detail__Files_SingleFile

**Comment by bdolly** [comment] 2019-05-08 16:59
@dankolbman is #219 a duplicate of this?

**Comment by dankolbman** [comment] 2019-05-08 17:07
@bdolly no, @219 is for the design, this is the implementation.

**Closed** 2019-05-21 18:59 UTC
Labels: feature
